2025-04-18 18:52:54,029 INFO    Thread-5  :4144289 [wandb_setup.py:_flush():68] Current SDK version is 0.19.1
2025-04-18 18:52:54,029 INFO    Thread-5  :4144289 [wandb_setup.py:_flush():68] Configure stats pid to 4144289
2025-04-18 18:52:54,029 INFO    Thread-5  :4144289 [wandb_setup.py:_flush():68] Loading settings from /speech/shoutrik/.config/wandb/settings
2025-04-18 18:52:54,030 INFO    Thread-5  :4144289 [wandb_setup.py:_flush():68] Loading settings from /speech/shoutrik/torch_exp/my_own/wandb/settings
2025-04-18 18:52:54,030 INFO    Thread-5  :4144289 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-04-18 18:52:54,030 INFO    Thread-5  :4144289 [wandb_init.py:_log_setup():528] Logging user logs to /speech/shoutrik/torch_exp/my_own/wandb/run-20250418_185254-l7vgm1ns/logs/debug.log
2025-04-18 18:52:54,030 INFO    Thread-5  :4144289 [wandb_init.py:_log_setup():529] Logging internal logs to /speech/shoutrik/torch_exp/my_own/wandb/run-20250418_185254-l7vgm1ns/logs/debug-internal.log
2025-04-18 18:52:54,030 INFO    Thread-5  :4144289 [wandb_init.py:init():644] calling init triggers
2025-04-18 18:52:54,030 INFO    Thread-5  :4144289 [wandb_init.py:init():650] wandb.init called with sweep_config: {'batch_norm': False, 'batch_size': 256, 'conv_activation': 'ReLU', 'data_aug': True, 'dense_activation': 'ReLU', 'dense_size': 1024, 'dropout_prob': 0.3, 'filter_size': [7, 7, 5, 3, 3], 'learning_rate': 0.001, 'n_epochs': 10, 'n_filter': [64, 64, 64, 64, 64], 'num_layers': 5, 'optimizer': 'adam', 'weight_decay': 0.005, 'weight_init': 'xavier'}
config: {}
2025-04-18 18:52:54,030 INFO    Thread-5  :4144289 [wandb_init.py:init():680] starting backend
2025-04-18 18:52:54,030 INFO    Thread-5  :4144289 [wandb_init.py:init():684] sending inform_init request
2025-04-18 18:52:54,035 INFO    Thread-5  :4144289 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-18 18:52:54,035 INFO    Thread-5  :4144289 [wandb_init.py:init():697] backend started and connected
2025-04-18 18:52:54,036 INFO    Thread-5  :4144289 [wandb_run.py:_config_callback():1279] config_cb None None {'batch_norm': False, 'batch_size': 256, 'conv_activation': 'ReLU', 'data_aug': True, 'dense_activation': 'ReLU', 'dense_size': 1024, 'dropout_prob': 0.3, 'filter_size': [7, 7, 5, 3, 3], 'learning_rate': 0.001, 'n_epochs': 10, 'n_filter': [64, 64, 64, 64, 64], 'num_layers': 5, 'optimizer': 'adam', 'weight_decay': 0.005, 'weight_init': 'xavier'}
2025-04-18 18:52:54,038 INFO    Thread-5  :4144289 [wandb_init.py:init():790] updated telemetry
2025-04-18 18:52:54,039 INFO    Thread-5  :4144289 [wandb_init.py:init():822] communicating run to backend with 90.0 second timeout
2025-04-18 18:52:54,614 INFO    Thread-5  :4144289 [wandb_init.py:init():874] starting run threads in backend
2025-04-18 18:52:54,744 INFO    Thread-5  :4144289 [wandb_run.py:_console_start():2374] atexit reg
2025-04-18 18:52:54,745 INFO    Thread-5  :4144289 [wandb_run.py:_redirect():2224] redirect: wrap_raw
2025-04-18 18:52:54,745 INFO    Thread-5  :4144289 [wandb_run.py:_redirect():2289] Wrapping output streams.
2025-04-18 18:52:54,745 INFO    Thread-5  :4144289 [wandb_run.py:_redirect():2314] Redirects installed.
2025-04-18 18:52:54,745 INFO    Thread-5  :4144289 [wandb_init.py:init():916] run started, returning control to user process
2025-04-18 18:52:59,384 INFO    Thread-5  :4144289 [wandb_run.py:_finish():2100] finishing run ee22s084-indian-institute-of-technology-madras/DL_assignment_02/l7vgm1ns
2025-04-18 18:52:59,384 INFO    Thread-5  :4144289 [wandb_run.py:_atexit_cleanup():2339] got exitcode: 1
2025-04-18 18:52:59,384 INFO    Thread-5  :4144289 [wandb_run.py:_restore():2321] restore
2025-04-18 18:52:59,384 INFO    Thread-5  :4144289 [wandb_run.py:_restore():2327] restore done
2025-04-18 18:53:00,384 WARNING MsgRouterThr:4144289 [router.py:message_loop():75] message_loop has been closed
2025-04-18 18:53:00,385 INFO    Thread-5  :4144289 [wandb_run.py:_restore():2321] restore
2025-04-18 18:53:00,385 INFO    Thread-5  :4144289 [wandb_run.py:_restore():2327] restore done
2025-04-18 18:53:00,386 ERROR   Thread-5  :4144289 [wandb_run.py:_atexit_cleanup():2360] Problem finishing run
Traceback (most recent call last):
  File "/speech/shoutrik/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/wandb/agents/pyagent.py", line 306, in _run_job
    self._function()
  File "sweep.py", line 37, in train_wrapper
    train_and_eval(args, logging=True)
  File "/speech/shoutrik/torch_exp/my_own/train.py", line 70, in train_and_eval
    loss = criterion(model(images), labels)
  File "/speech/shoutrik/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/speech/shoutrik/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/speech/shoutrik/torch_exp/my_own/model.py", line 45, in forward
    x = self.feature_extractor(x)
  File "/speech/shoutrik/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/speech/shoutrik/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/speech/shoutrik/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/container.py", line 219, in forward
    input = module(input)
  File "/speech/shoutrik/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/speech/shoutrik/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/speech/shoutrik/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 458, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/speech/shoutrik/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 454, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.06 GiB. GPU 0 has a total capacity of 47.50 GiB of which 836.25 MiB is free. Including non-PyTorch memory, this process has 46.68 GiB memory in use. Of the allocated memory 46.19 GiB is allocated by PyTorch, and 4.83 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/speech/shoutrik/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2351, in _atexit_cleanup
    self._on_finish()
  File "/speech/shoutrik/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2608, in _on_finish
    _ = exit_handle.wait(
  File "/speech/shoutrik/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 279, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/speech/shoutrik/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/speech/shoutrik/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 122, in _wait
    return self._event.wait(timeout=timeout)
  File "/speech/shoutrik/espnet/tools/anaconda/envs/espnet/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/speech/shoutrik/espnet/tools/anaconda/envs/espnet/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
Exception
